language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
branches:
  only:
    - master
script:
  - npm prune
  - npm run lint
  - npm run coverage
  - npm run report
  - npm run build
after_success:
  - npm install -g travis-deploy-once
  - travis-deploy-once "npm run semantic-release"
